Implement id generator for player id
yoyojin-tcs/dice_game pull request #1
Opened 2023-10-11 21:01 UTC by BlTniki

Реализовал достаточно поверхностно, так что жду плотных оплеух. Ещё я не уверен в выборе пакетов и названий, тут тоже жду комментариев.

Добавил новый интерфейс `IdGenerator` с методом `generateId()`. Также написал реализацию. Она реализует стратегию инкремента id после каждой генерации, а также реализует паттерн синглтон, так что мы можем быть уверенны, что счётчик не собьётся.

2023-10-11 21:13 UTC, yoyojin-tcs commented
Подумай как мы в таком случае будем обеспечивать уникальность пользователей по ID?
Я могу в Person сам положить что захочу.
Так ли необходим здесь синглтон? Можно ли сделать без него?
Что если мы захотим использовать эту стратегию не только для генерации ID пользователей, но и для генерации ID кубиков?

2023-10-12 14:15 UTC, yoyojin-tcs requested changes
См. общий коммент к PR

2023-10-12 14:31 UTC, BlTniki commented
Да, я увидел и теперь много думаю над этим)
Просто пока не дошли руки до реализации.

Но раз уж я тут, опишу свою идею как покрыть хотя бы часть ваших вопросов: Моя идея отказаться от синглтона в классе `...IdGenerationStrategy` и реализовать фабрику создания **игроков**. 
Эту фабрику можно будет конфигурировать различными сущностями `IdGenerator` (можно будет даже mock-нуть его) и впрыскивать сконфигурированную фабрику в любые классы, что занимаются созданием игроков
При этом я не хочу как либо приватить конструктор игрока, так как хочу оставить возможность загружать игрока из БД, например. А в таком случае его Id уже будет определён (хотя тут всё зависит от целей Id. Нужен ли он для хранения в базе или он просто для различения игроков с одинаковым именем в течении одной сессии)

2023-10-12 18:14 UTC, BlTniki commented
Сделал изменения, теперь постараюсь описать, как они отвечают на ваши вопросы:
`Так ли необходим здесь синглтон?`
Действительно нет в нём необходимости. В данном коде я обошёлся `Dependency Injection`.

`Подумай как мы в таком случае будем обеспечивать уникальность пользователей по ID?
Я могу в Person сам положить что захочу.`
Чтобы избежать ошибок в клиентском коде и оставить класс `Player` минимально зависимым от внешнего кода, я выделил логику создания игрока в отдельную "фабрику" `PlayerFacrory`. Называть её фабрикой это сильно конечно, но идею передаёт. А также я сделал конструктор игрока `protected`.

`Что если мы захотим использовать эту стратегию для генерации ID кубиков?`
Ну собственно теперь стратегия не одиночка, так что ничто не мешает нам создать ещё одну сущность и для кубиков.

2023-10-12 20:35 UTC, yoyojin-tcs commented on src/com/yoyojin/edu/dice_game/idGenerator/IncrementIdGeneratorStrategy.java
> +public class IncrementIdGeneratorStrategy implements IdGenerator {
В такой реализации вижу потенциальный exception. Подумай, где и какой?

2023-10-12 20:35 UTC, yoyojin-tcs commented on src/com/yoyojin/edu/dice_game/models/player/Player.java
> +    protected Player(Long id, String name) {
область видимости protected позволяет переопределить метод у классов наследников, причём и в других пакетах тоже.

2023-10-12 20:35 UTC, yoyojin-tcs commented on src/com/yoyojin/edu/dice_game/models/player/Player.java
> +        if (id == null || id < 0) {
если мы задаём конструктору ограниченную область видимости, точно ли валидация данных его задача?

2023-10-12 20:35 UTC, yoyojin-tcs commented on src/com/yoyojin/edu/dice_game/models/player/PlayerFactory.java
> +    public Player makePlayer(final String name) {
Точно ли make? Мне кажется create или register было бы как-то логичнее, мы же не прям "делаем" игрока, а регистрируем/создаём :)

2023-10-12 20:35 UTC, yoyojin-tcs commented on src/com/yoyojin/edu/dice_game/models/player/PlayerFactory.java
> +public class PlayerFactory {
Идея с фабрикой мне нравится.
Такое решение более поддерживаемое и расширяемое.
В дальнейшем, если, допустим, мы захотим добавить какие-то особенности игрокам, сможем выделить интерфейс, а на основе входных данных решать какую именно реализацию выбрать.

2023-10-13 15:13 UTC, yoyojin-tcs commented on src/com/yoyojin/edu/dice_game/models/player/PlayerFactory.java
> +        Objects.requireNonNull(name);
Пустая строка в таком случае отловится?

2023-10-13 19:07 UTC, BlTniki commented on src/com/yoyojin/edu/dice_game/models/player/Player.java
> +        if (id == null || id < 0) {
Всегда думал, что модификатор по умолчанию это `protected` 0_o

2023-10-13 19:10 UTC, BlTniki commented on src/com/yoyojin/edu/dice_game/idGenerator/IncrementIdGeneratorStrategy.java
> +public class IncrementIdGeneratorStrategy implements IdGenerator {
Нуу переполнение лонга ошибку не кинет, так думаю, что мы можем закинуть `null` в конструктор. Собственно добавил везде проверку на  `null`

2023-10-17 21:45 UTC, yoyojin-tcs commented on src/com/yoyojin/edu/dice_game/models/player/Player.java
> +        if (id == null || id < 0) {
По умолчанию модификатор package, в таком случае область видимости будет только внутри пакета.

2023-10-17 21:46 UTC, merged